{
  "artifacts": [],
  "command": "my_main",
  "experiment": {
    "base_dir": "/Users/xumingyuan/Documents/repository/Unity_epymarl/src",
    "dependencies": [
      "numpy==1.23.5",
      "PyYAML==5.3.1",
      "sacred==0.8.7",
      "torch==2.5.1"
    ],
    "mainfile": "main.py",
    "name": "pymarl",
    "repositories": [
      {
        "commit": "45108674e4d0c32cce809eb475101f76fb43ffee",
        "dirty": true,
        "url": "git@github.com:xmy86/Unity_epymarl.git"
      },
      {
        "commit": "45108674e4d0c32cce809eb475101f76fb43ffee",
        "dirty": true,
        "url": "git@github.com:xmy86/Unity_epymarl.git"
      },
      {
        "commit": "45108674e4d0c32cce809eb475101f76fb43ffee",
        "dirty": true,
        "url": "git@github.com:xmy86/Unity_epymarl.git"
      }
    ],
    "sources": [
      [
        "main.py",
        "_sources/main_b2cc1db06d11795e4f8cf6a3b0165fa1.py"
      ],
      [
        "run.py",
        "_sources/run_29fd448eb2929a57e5fd2547c431175b.py"
      ],
      [
        "utils/logging.py",
        "_sources/logging_80685d67fab61f6e71e93fbe28085531.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/Users/xumingyuan/Documents/repository/Unity_epymarl/src/envs/gymma.py\", line 67, in __init__\n    self._env.unwrapped.seed(self._seed)\n",
    "AttributeError: 'UnityWrapper' object has no attribute 'seed'\n",
    "\nDuring handling of the above exception, another exception occurred:\n\n",
    "Traceback (most recent call last):\n",
    "  File \"/opt/anaconda3/envs/epymarl/lib/python3.10/site-packages/sacred/config/captured_function.py\", line 42, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"/Users/xumingyuan/Documents/repository/Unity_epymarl/src/main.py\", line 44, in my_main\n    run(_run, config, _log)\n",
    "  File \"/Users/xumingyuan/Documents/repository/Unity_epymarl/src/run.py\", line 67, in run\n    run_sequential(args=args, logger=logger)\n",
    "  File \"/Users/xumingyuan/Documents/repository/Unity_epymarl/src/run.py\", line 100, in run_sequential\n    runner = r_REGISTRY[args.runner](args=args, logger=logger)\n",
    "  File \"/Users/xumingyuan/Documents/repository/Unity_epymarl/src/runners/episode_runner.py\", line 24, in __init__\n    self.env = env_REGISTRY[self.args.env](\n",
    "  File \"/Users/xumingyuan/Documents/repository/Unity_epymarl/src/envs/__init__.py\", line 33, in gymma_fn\n    return GymmaWrapper(**kwargs)\n",
    "  File \"/Users/xumingyuan/Documents/repository/Unity_epymarl/src/envs/gymma.py\", line 69, in __init__\n    self._env.reset(seed=self._seed)\n",
    "  File \"/Users/xumingyuan/Documents/repository/Unity_epymarl/src/envs/wrappers.py\", line 27, in reset\n    obs, info = self.env.reset(seed=seed, options=options)\n",
    "  File \"/opt/anaconda3/envs/epymarl/lib/python3.10/site-packages/gymnasium/wrappers/common.py\", line 146, in reset\n    return super().reset(seed=seed, options=options)\n",
    "  File \"/opt/anaconda3/envs/epymarl/lib/python3.10/site-packages/gymnasium/core.py\", line 328, in reset\n    return self.env.reset(seed=seed, options=options)\n",
    "  File \"/opt/anaconda3/envs/epymarl/lib/python3.10/site-packages/gymnasium/wrappers/common.py\", line 400, in reset\n    return super().reset(seed=seed, options=options)\n",
    "  File \"/opt/anaconda3/envs/epymarl/lib/python3.10/site-packages/gymnasium/core.py\", line 328, in reset\n    return self.env.reset(seed=seed, options=options)\n",
    "  File \"/opt/anaconda3/envs/epymarl/lib/python3.10/site-packages/gymnasium/wrappers/common.py\", line 293, in reset\n    return env_reset_passive_checker(self.env, seed=seed, options=options)\n",
    "  File \"/opt/anaconda3/envs/epymarl/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py\", line 197, in env_reset_passive_checker\n    check_obs(obs, env.observation_space, \"reset\")\n",
    "  File \"/opt/anaconda3/envs/epymarl/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py\", line 143, in check_obs\n    assert len(obs) == len(\n",
    "AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 5, space length: 2\n"
  ],
  "heartbeat": "2024-12-12T03:35:57.754777",
  "host": {
    "ENV": {},
    "cpu": "Apple M3",
    "hostname": "xmy-mba.local",
    "os": [
      "Darwin",
      "macOS-15.0.1-arm64-arm-64bit"
    ],
    "python_version": "3.10.12"
  },
  "meta": {
    "command": "my_main",
    "config_updates": {
      "env_args": {
        "key": "unity_env",
        "time_limit": 25
      }
    },
    "named_configs": [],
    "options": {
      "--beat-interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--id": null,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print-config": false,
      "--priority": null,
      "--queue": false,
      "--s3": null,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [
        "env_args.time_limit=25",
        "env_args.key=\"unity_env\""
      ],
      "help": false,
      "with": true
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2024-12-12T03:35:52.302167",
  "status": "FAILED",
  "stop_time": "2024-12-12T03:35:57.763118"
}